version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gabriela.campoverde@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"